check for SDR in cont-init but actually grab device index in SDR startup script

diff --git a/rootfs/etc/templates/run b/rootfs/etc/templates/run
--- a/rootfs/etc/templates/run
+++ b/rootfs/etc/templates/run
@@ -12,16 +12,34 @@ fi
 set -e
 
 VDLM_BIN="/usr/local/bin/dumpvdl2"
-DEVICE_ID=""
 # shellcheck disable=SC2001
 FREQ_STRING=""
 VDLM_CMD=()
 
 # Specify device ID
-if [ -n "${DEVICE_ID}" ]; then
-	VDLM_CMD+=("--rtlsdr" "$DEVICE_ID")
-elif [ -n "${SOAPYSDR}" ]; then
+if [ -n "${SOAPYSDR}" ]; then
 	VDLM_CMD+=("--soapysdr" "$SOAPYSDR")
+elif [ -n "${SERIAL}" ]; then
+	mapfile -t RTL_TEST_OUTPUT < <(timeout 1s rtl_test -d 0 2>&1 | grep -P '^\s+\d+:\s.*?,.*?,\s+SN:\s+.*?$' | IFS=$'\n' sed -n 's/^\s*\([^:]*\):[^,]*,[^,]*,\s*SN:\s*\(.*\)$/\1,\2/; s/\s*$//p' || true)
+	for RTL_TEST_OUTPUT_LINE in "${RTL_TEST_OUTPUT[@]}"; do
+			if [[ "${RTL_TEST_OUTPUT_LINE##*,}" == "$SERIAL" ]]; then
+					OUTPUT_DEVICE_ID="${RTL_TEST_OUTPUT_LINE%%,*}"
+			fi
+	done
+
+	if [[ -z "${OUTPUT_DEVICE_ID}" ]]; then
+			echo "Could not find Device ID for serial '$SERIAL'"
+			exit 1
+	fi
+
+	rm -rf /etc/services.d/dumpvdl2/run > /dev/null 2>&1
+	if [[ -n "${OUTPUT_DEVICE_ID}" ]]; then
+		VDLM_CMD+=("--rtlsdr" "$OUTPUT_DEVICE_ID")
+	else
+		echo "Could not find Device ID for serial '$SERIAL'"
+    sleep 60
+    exit 1
+	fi
 fi
 
 if [ -n "$CENTER_FREQ" ]; then
